from flask import Flask, request, jsonify, Response, redirect
from urllib.parse import urlencode
from datetime import datetime, timezone
import requests
import base64
import json

app = Flask(__name__)

@app.route("/", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"])
def proxy(path):
    headers_to_forward = {key: value for key, value in request.headers if key.lower() != "host"}
    
    target_url = f"https://{request.headers.get("Host").split(".")[0]}.playfabapi.com/{path}"

    headers_to_forward = {}
    for header in ["X-EntityToken", "X-Authorization", "Content-Type", "X-SecretKey"]:
        if header in request.headers:
            headers_to_forward[header] = request.headers[header]

    body = request.get_json(force=True)
    
    body["keys"] = None
    
    resp = requests.request(
        method=request.method,
        url=target_url,
        headers=headers_to_forward,
        data=json.dumps(body),
        params=request.args,
        allow_redirects=False
    )

    print(f"to: {target_url}")
    print(f"headers: {headers_to_forward}")
    print(f"body: {request.get_data()}")

    if path == "Client/GetUserInventory":
        return {
          "code": 200,
          "data": {
            "Inventory": [
              {
                "CatalogVersion": "DLC",
                "DisplayName": "LBAAD.",
                "ItemId": "LBAAD.",
                "ItemInstanceId": "3ECA24CB0BDE2BD4",
                "PurchaseDate": "2026-01-16T06:10:55.19Z",
                "UnitPrice": 0
              },
              {
                "CatalogVersion": "DLC",
                "DisplayName": "LBADE.",
                "ItemId": "LBADE.",
                "ItemInstanceId": "3ECA24CB0BDE2BD4",
                "PurchaseDate": "2026-01-16T06:10:55.19Z",
                "UnitPrice": 0
              },
              {
                "CatalogVersion": "DLC",
                "DisplayName": "LBACP.",
                "ItemId": "LBACP.",
                "ItemInstanceId": "3ECA24CB0BDE2BD4",
                "PurchaseDate": "2026-01-16T06:10:55.19Z",
                "UnitPrice": 0
              },
              {
                "CatalogVersion": "DLC",
                "DisplayName": "LBAAK.",
                "ItemId": "LBAAK.",
                "ItemInstanceId": "3ECA24CB0BDE2BD4",
                "PurchaseDate": "2026-01-16T06:10:55.19Z",
                "UnitPrice": 0
              },
              {
                "CatalogVersion": "DLC",
                "DisplayName": "LBAGS.",
                "ItemId": "LBAGS.",
                "ItemInstanceId": "3ECA24CB0BDE2BD4",
                "PurchaseDate": "2026-01-16T06:10:55.19Z",
                "UnitPrice": 0
              },
              {
                "CatalogVersion": "DLC",
                "DisplayName": "LFAAZ.",
                "ItemId": "LFAAZ.",
                "ItemInstanceId": "3ECA24CB0BDE2BD4",
                "PurchaseDate": "2026-01-16T06:10:55.19Z",
                "UnitPrice": 0
              },
              {
                "CatalogVersion": "DLC",
                "DisplayName": "LHABR.",
                "ItemId": "LHABR.",
                "ItemInstanceId": "3ECA24CB0BDE2BD4",
                "PurchaseDate": "2026-01-16T06:10:55.19Z",
                "UnitPrice": 0
              },
              {
                "CatalogVersion": "DLC",
                "DisplayName": "LFAAF.",
                "ItemId": "LFAAF.",
                "ItemInstanceId": "3ECA24CB0BDE2BD4",
                "PurchaseDate": "2026-01-16T06:10:55.19Z",
                "UnitPrice": 0
              }
            ],
            "VirtualCurrency": {
              "SR": 999999999
            },
            "VirtualCurrencyRechargeTimes": {
              "SR": {
                "RechargeMax": 999999999,
                "RechargeTime": "2026-01-16T06:29:31.512Z",
                "SecondsToRecharge": 8
              }
            }
          },
          "status": "OK"
        }

    try:
        response_data = resp.json()
        print("JSON Response:", response_data)
        if path == "Client/GetSharedGroupData":
            data_block = response_data.get("data", {}).get("Data", {})
        
            if isinstance(data_block, dict) and data_block:
        
                print("keys:", list(data_block.keys()))
        
                try:
                    original_body = request.get_json(force=True) or {}
                except Exception:
                    original_body = {}
        
                shared_group_id = original_body.get("SharedGroupId")
        
                if shared_group_id:
                    cosmetic_value = "Early Access Supporter Pack 1000SHINYROCKS2200SHINYROCKS5000SHINYROCKSDAILY LOGINLBAAA.LBAAB.LBAAC.LBAAD.LBAAF.LBAAG.LBAAH.LBAAI.LBAAJ.LFAAA.LFAAB.LFAAC.LFAAD.LFAAE.LFAAF.LFAAG.LFAAH.LFAAI.LFAAJ.LFAAK.LFAAL.LFAAM.LFAAN.LFAAO.LHAAA.LHAAB.LHAAC.LHAAD.LHAAE.LHAAF.LHAAH.LHAAI.LHAAJ.LHAAK.LHAAL.LHAAM.LHAAN.LHAAO.LHAAP.LHAAQ.LHAAR.LHAAS.FIRST LOGINLHAAG.LBAAE.LBAAK.LHAAT.LHAAU.LHAAV.LHAAW.LHAAX.LHAAY.LHAAZ.LFAAP.LFAAQ.LFAAR.LFAAS.LFAAT.LFAAU.LBAAL.LBAAM.LBAAN.LBAAO.LSAAA.LSAAB.LSAAC.LSAAD.LHABA.LHABB.LHABC.LFAAV.LFAAW.LBAAP.LBAAQ.LBAAR.LBAAS.LFAAX.LFAAY.LFAAZ.LFABA.LHABD.LHABE.LHABF.LHABG.LSAAE.LFABB.LFABC.LHABH.LHABI.LHABJ.LHABK.LHABL.LHABM.LHABN.LHABO.LBAAT.LHABP.LHABQ.LHABR.LFABD.LBAAU.LBAAV.LBAAW.LBAAX.LBAAY.LBAAZ.LBABA.LBABB.LBABC.LBABD.LBABE.LFABE.LHABS.LHABT.LHABU.LHABV.LFABF.LFABG.LBABF.LBABG.LHABW.LBABH.LHABX.LHABY.LMAAA.LMAAB.LHABZ.LHACA.LBABJ.LBABK.LBABL.LMAAC.LMAAD.LMAAE.LBABI.LMAAF.LMAAG.LMAAH.LFABH.LHACB.LHACC.LFABI.LBABM.LBABN.LHACD.LMAAI.LMAAJ.LMAAK.LMAAL.LMAAM.LMAAN.LMAAO.LHACE.LFABJ.LFABK.LFABL.LFABM.LFABN.LFABO.LBABO.LBABP.LMAAP.LBABQ.LBABR.LBABS.LBABT.LBABU.LFABP.LFABQ.LFABR.LHACF.LHACG.LHACH.LMAAQ.LMAAR.LMAAS.LMAAT.LMAAU.LMAAV.LSAAF.LSAAG.LHACI.LFABS.LFABT.LBABV.LHACJ.LHACK.LBABW.LHACL.LBABX.LFABU.LFABV.LBABY.LHACN.LHACO.LBABZ.LHACM.LMAAW.LMAAX.LMAAY.LMAAZ.LMABA.LMABB.LMABC.LSAAI.LSAAJ.LSAAK.LSAAL.LSAAM.LMABD.LMABE.LMABF.LMABG.LMABH.LMABI.LMABJ.LMABK.LMABL.LMABM.LHACP.LMABN.LMABO.LFABW.LHACQ.LHACR.LMABP.LMABQ.LMABR.LMABS.LHACS.LMABT.LBACA.LMABU.LBACB.LHACT.LHACU.LHACV.LBACC.LMABV.LMABW.LHACW.LHACX.LHACY.LBACD.LBACE.LBACF.LHACZ.LMABX.LMABY.LMABZ.LMACA.LBACG.LHADA.LSAAN.LSAAO.LSAAP2.S. FIRST LOGINLHADB.LHADC.LHADD.LHADE.LHADF.LHADG.LFABX.LFABY.LBACH.LBACI.LMACB.LMACC.LMACD.LSAAP.LSAAQ.LMACE.LMACF.LBACK.LBACJ.LHADH.LMACG.LMACH.LMACI.LMACJ.LSAAR.LMACK.LSAAP.2. (1)LFABZ.LFACA.LMACL.game-purchase-bundleLHADI.LHADJ.LHADK.LHADL.LFACB.LFACC.LFACD.LBACL.LBACM.LBACN.LBACO.LBACP.LMACM.LMACN.LMACO.LMACP.LMACQ.LMACR.LMACS.LMACT.LMACU.LMACV.LMACW.LMACX.LMACY.LHADM.LBACQ.LBACR.LBACS.LSAAS.LHADN.LHADO.LHADP.LFACE.LFACF.LBACT.LBACU.LBACV.LBACW.LMACZ.LMADA.LMADB.LMADC.LMADD.LMADE.LHADQ.LMADG.LMADF.LMADH.LMADI.LMADJ.LMADK.LSAAT.LMADL.LSAAU.LHADR.LHADS.LHADT.LHADU.LHADV.LFACG.LFACH.LFACI.LFACJ.LMADM.LMADN.LMADO.LMADP.LMADQ.LMADR.LMADS.LMADT.LMADU.LMADV.LBACX.LBACY.LBACZ.LBADA.LSAAV.LSAAW.LSAAY.LSAAX.LBADB.LHADW.LHADX.LHADY.LFACK.LBADC.LBADD.LMADW.LMADX.LMADY.LMADZ.LMAEA.LMAEB.LMAEC.LMAED.LMAEE.LMAEF.LMAEG.LMAEH.LMAEI.LBADE.LHADZ.LMAEJ.LHAEA.LHAEB.LFACL.LMAEK.LMAEL.LMAEM.LMAEN.LHAEC.LHAED.LHAEE.LFACM.LFACN.LMAEO.LMAEP.LMAEQ.LMAER.LMAES.LMAET.LBADF.LBADG.LBADH.LBADI.LBADJ.LBADK.LBADL.LBADM.LSAAZ.LSABA.LMAEU.LBADN.LMAEZ.LHAEF.LHAEG.LHAEH.LHAEI.LFACO.LFACP.LBADO.LBADP.LBADQ.LMAEV.LMAEW.LMAEX.LMAEY.LMAFA.LMAFB.LMAFC.LMAFD.LMAFE.LMAFF.LMAFG.LMAFH.LMAFI.LSABB.LHAEJ.LHAEK.LHAEL.LHAEM.LFACQ.LFACR.LFACS.LBADR.LBADS.LBADT.LBADU.LBADV.LMAFJ.LMAFK.LMAFL.LMAFM.LMAFN.LMAFO.LMAFP.LMAFQ.LMAFR.LMAFS.LFACT.LFACU.LFACV.LFACW.LFACX.LFACY.LFACZ.LSABC.LHAEN.LHAEO.LHAEP.LFADA.LFADB.LFADC.LFADD.LBADW.LBADX.LBADY.LBADZ.LMAFT.LMAFU.LMAFV.LMAFW.LMAFX.LMAFY.LMAFZ.LMAGA.LMAGB.LMAGC.LMAGD.LMAGE.LHAEQ.LHAER.LHAES.LHAET.LHAEU.LFADE.LBAEA.LBAEB.LBAEC.LBAED.LBAEE.LMAGF.LMAGG.LMAGH.LMAGI.LMAGJ.LMAGK.LMAGL.LMAGM.LMAGN.LMAGO.LMAGP.LMAGQ.LHAEV.LHAEW.LHAEX.LHAEY.LFADF.LFADG.LFADH.LFADI.LBAEF.LBAEG.LBAEH.LMAGR.LMAGS.LMAGT.LMAGU.LMAGV.LMAGW.LMAGX.LMAGY.LMAGZ.LSABD.LBAEI.LHAEZ.LHAFA.LHAFB.LHAFC.LBAEJ.LBAEK.LBAEL.LBAEM.LBAEN.LMAHA.LMAHB.LMAHD.LMAHE.GT 1000SHINYROCKSGT2200SHINYROCKSGT5000SHINYROCKSSPIDERMONKEBUNDLLMAHF.LMAHG.LMAHI.LMAHJ.LMAHK.LMAHM.LMAHN.LMAHO.LMAHP.LHAFD.LMAHQ.LMAHR.LHAFE.LHAFF.LHAFG.LFADJ.LFADK.LBAEO.LBAEP.LBAEQ.LBAER.LBAES.LMAHS.LSABE.LHAFH.LHAFI.LHAFJ.LFADL.LFADM.LBAET.LBAEU.LBAEV.LBAEW.LBAEX.LMAHT.LMAHU.LMAHV.LMAHX.LMAHY.LMAHZ.LMAIA.LMAIB.LMAIC.LMAHW.LMAID.LSABF.LMAIE.LMAIF.LBAEY.LBAEZ.LBAFA.LBAFB.LBAFC.LBAFD.LBAFE.LBAFF.LBAFG.LBAFH.LHAFL.LHAFM.LHAFN.LHAFO.LHAFP.LFADN.LFADO.LBAFI.LBAFJ.LBAFK.LBAFL.LBAFM.LBAFN.LMAIG.LMAIH.LMAII.LMAIJ.LMAIK.LMAIL.LHAFK.LSABG.LBAFO.LBAFP.LBAFQ.LBAFR.LMAIM.LMAIN.LMAIO.LMAIP.LBAFS.LHAFQ.LMAIQ.LSABH.LBAFT.LHAFR.LMAIR.LBAFU.LHAFS.LHAFT.LFADP.LFADQ.LMAIS.LMAIT.LMAIU.LMAIV.LMAIX.LHAFU.LBAFV.LBAFW.LHAFV.LBAFX.LMAJA.1 1000SHINYROCKSLSABI.LMAIW.LMAIY.LMAIZ.LHAFW.LHAFX.LHAFY.LHAFZ.LFADR.LFADS.LFADT.LFADU.LBAFY.LBAFZ.LBAGA.LBAGB.LBAGC.LBAGD.LMAJB.LMAJC.LMAJD.LMAJE.LMAJF.LMAJG.LSABJ.LMAJH.LMAJI.LFADV.LFADW.LHAGA.LHAGB.LHAGC.LBAGE.LBAGF.LBAGG.LBAGH.LBAGI.LBAGJ.LBAGK.LMAJJ.LMAJK.LMAJL.LMAJN.LMAJO.LMAJP.LMAJQ.LMAJM.LSABK.LHAGD.LHAGE.LFADX.LFADY.LBAGL.LBAGM.LBAGN.LBAGO.LBAGP.LBAGQ.LBAGR.LMAJR.LMAJS.LMAJT.LMAJU.LMAJV.LMAJW.LMAJX.LMAJY.LMAJZ.LMAKA.LMAKB.LSABL.LMAKC.LBAGS.LHAGF.LHAGG.LHAGH.LHAGI.LHAGJ.LFADZ.LFAEA.LBAGT.LBAGU.LBAGV.LBAGW.LMAKD.LMAKE.LMAKF.LMAKH.LMAKI.LMAKJ.LMAKK.LMAKL.LMAKM.LMAKG.LBAGX.LMAKN.LMAKO.LMAKP.LSABM.LSABN.LHAGK.LHAGL.LHAGM.LHAGN.LHAGO.LFAEB.LFAEC.LBAGY.LBAGZ.LBAHA.LBAHB.LBAHC.LBAHD.LMAKQ.LMAKR.LMAKS.LMAKV.LMAKU.LMAKT.LSABO.LMAKW.LHAGP.LHAGQ.LHAGR.LFAED.LFAEE.LFAEF.LFAEG.LBAHE.LBAHF.LBAHG.LBAHH.LBAHI.LBAHJ.LBAHK.LBAHL.LBAHM.LBAHN.LMAKX.LMAKY.LMAKZ.LMALA.LMALB.LMALC.LMALD.LMALE.LMALF.LMALG.LSABP.LMALH.1 1000SHINYROCKSPGLAMROCKERBUNDLELMALI.LHAGS.LSABQ.CLIMBSTOPPERSBUNLHAGT.LBAHO.LBAHP.LHAGU.LHAGV.LFAEH.LFAEI.LHAGX.LHAGW.LBAHQ.LMALJ.LMALK.LMALL.LBAHT.LBAHR.LBAHS.LMALM.LHAGY.LMALN.LBAHU.LMALO.LMALP.LMALQ.LMALR.LSABR.LFAEJ.LFAEK.LBAHW.LBAHX.LHAHA.LHAHB.LMALS.LMALU.LMALT.LHAGZ.LBAHV.LFAEL.LBAHY.LBAHZ.LHAHC.LBAIA.LMALW.LMALX.LSABS.LHAHD.LFAEM.LFAEN.LBAIB.LMALV.LMALY.LHAHG.LHAHF.LHAHE.LMALZ.LBAIC.LMAMA.LMAMB.LBAID.LMAMC.LMAMD.LBAIF.LFAEO.LFAEP.LHAHH.LBAIG.LHAHI.LMAME.LMAMF.LMAMG.LMAMH.LMAMI.LFAEQ.LMAMJ.LFAES.LMAMK.LBAII.LBAIH.LBAIJ.LMAML.LMAMM.LSABT.LMAMN.LMAMO.LMAMP.LHAHK.LEAAA.LEAAB.LBAIK.LBAIL.LMAMR.LMAMQ.LFAER.LHAHJ.LHAHL.LBAIM.LMAMS.LMAMT.LDAAA.LMAMU.LMAMV.LMAMW.LBAIN.LHAHM.LMAMX.LHAHN.LMAMY.LMAMZ.LBAIO.LBAIP.LMANA.LFAET.LBAIQ.LBAIR.LBAIS.LMANB.LSABU.LHAHO.LFAEU.LBAIU.LHAHP.LBAIV.LBAIT.LMAND.LMANC.LHAHQ.LBAIW.LDAAB.LHAHR.LHAHS.LHAHT.LHAHU.LBAIX.LBAIY.LBAIZ.LBAJA.LBAJB.LFAEV.LBAJC.LBAJD.LFAEW.LBAJE.LHAHV.LMANE.LMANF.LMANG.LMANH.LMANI.LMANJ.LSABV.LMANK.LMANL.LMANM.LMANN.LMANO.LMANP.LMANQ.LBAJF.LHAHW.LBAJG.LFAEX.LDAAC.LMANR.LBAJH.LBAJI.LFAEY.LHAHX.LHAHY.LHAHZ.LMANT.LMANS.LSABW.LMANU.LMANV.LMANW.LMANX.LBAJJ.LBAJK.LBAJL.LBAJM.LMANY.LBAJN.LBAJO.LMANZ.LMAOA.LDAAD.LDAAE.LMAOB.LMAOC.LMAOD.LEAAC.LMAOE.LMAOF.LHAIA.LHAIB.LBAJP.LMAOG.LHAIC.LBAJQ.LMAOH.LMAOI.LMAOJ.LMAOK.LMAOL.LMAOM.LMAON.LMAOO.LBAJR.LMAOP.LDAAF.LSABX.LMAOQ.LMAOR.LMAOS.LHAID.LHAIE.LBAJS.LMAOT.LEAAD.LFAEZ.LMAOU.LFAFA.LFAFB.LFAFC.LMAOV.LMAOW.LMAOX.LMAOY.LBAJT.LBAJU.LFAFD.LBAJV.LBAJW.LBAJX.LBAJY.LHAIF.LBAJZ.LHAIG.LHAIH.LMAOZ.LMAPA.LHAII.LMAPB.LBAKA.LBAKB.LHAIJ.LHAIK.LFAFE.LFAFG.LMAPC.LHAIL.LHAIM.LMAPD.LBAKC.LBAKD.LBAKE.LMAPE.LMAPF.LMAPG.LHAIN.LMAPH.LFAFH.LMAPI.LMAPJ.LSABY.LMAPK.LSABZ.LFAFI.LBAKF.LBAKG.LFAFJ.LMAPL.LMAPM.LBAKH.LHAIO.LFAFK.LBAKI.LHAIP.LHAIQ.LBAKJ.LBAKK.LBAKL.LBAKM.LBAKN.LMAPN.LHAIR.LHAIS.LHAIT.LBAKO.LFAFL.LMAPO.LFAFM.LBAKP.LHAIU.LBAKQ.LMAPP.LFAFN.LFAFO.LBAKR.LBAKS.LFAFP.LHAIV.LBAKT.LBAKU.LBAKV.LFAFQ.LMAPQ.LMAPR.LMAPS.LBAKW.LHAIW.LHAIX.LBAKX.LMAPT.LMAPU.LMAPV.LBAKY.LMAPW.LDAAG.LSACA.LMAPX.LMAPY.LBAKZ.LBALA.LMAPZ.LMAQA.LMAQB.LMAQC.LFAFR.LHAIY.LFAFS.LMAQD.LHAIZ.LBALB.LBALC.LHAJA.LHAJB.LHAJC.LHAJD.LFAFT.LBALD.LBALE.LBALF.LMAQE.LMAQF.LBALG.LFAFU.LMAQG.LHAJE.LFAFV.LFAFW.LSACB.LSACD.LSACC.LBALH.LHAJF.LFAFX.LBALI.LBALJ.LBALK."
        
                    updated_data = {
                        key: cosmetic_value
                        for key in data_block.keys()
                    }
        
                    update_payload = {
                        "SharedGroupId": shared_group_id,
                        "Data": updated_data,
                        "AuthenticationContext": None
                    }
        
                    update_url = (
                        f"https://"
                        f"{request.headers.get('Host').split('.')[0]}"
                        f".playfabapi.com/Client/UpdateSharedGroupData"
                    )
        
                    print("data:", update_payload)
        
                    requests.post(
                        url=update_url,
                        headers=headers_to_forward,
                        json=update_payload
                    )
            
        return jsonify(response_data), resp.status_code
    except ValueError:
        return Response(resp.content, status=resp.status_code, headers=dict(resp.headers))